# Generated by Django 4.2.30 on 2026-04-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='مقدار تخفیف')),
                ('start_data', models.DateTimeField(blank=True, null=True, verbose_name='شروع تاریخ تخفیف')),
                ('end_data', models.DateTimeField(blank=True, null=True, verbose_name='پایان تخفیف')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیفات',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='نام محصول')),
                ('price', models.IntegerField(verbose_name='قیمت کالا')),
                ('image', models.ImageField(upload_to='images/product', verbose_name='تصویر کالا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حدف شده / نشده')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.discount', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
