# Generated by Django 4.2.30 on 2026-04-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_amazing',
            field=models.BooleanField(default=False, verbose_name='محصول شگفت انگیز'),
        ),
    ]
