# Generated by Django 4.2.30 on 2026-04-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_product_is_amazing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان اسلایدر')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='لینک')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='تصویر اسلایدر')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'سلایدر',
                'verbose_name_plural': 'اسلایدر ها',
            },
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
