# Generated by Django 4.2.30 on 2026-04-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_slider_rename_end_data_discount_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.AddField(
            model_name='slider',
            name='image_md',
            field=models.ImageField(blank=True, null=True, upload_to='images/slider', verbose_name='تصویر اسلایدر در انداره کامپیوتر'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_sm',
            field=models.ImageField(blank=True, null=True, upload_to='images/slider', verbose_name='تصویر اسلایدر در اندازه موبایل'),
        ),
    ]
