# Generated by Django 4.2.30 on 2026-04-17 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_remove_slider_image_slider_image_md_slider_image_sm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='slug',
        ),
    ]
