# Generated by Django 4.2.30 on 2026-04-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_maincategory_childcategory_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childcategory',
            options={'verbose_name': 'دسته بندی فرزند', 'verbose_name_plural': 'دسته بندی های فرزند'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'دسته بندی اصلی', 'verbose_name_plural': 'دسته بندی های اصلی'},
        ),
        migrations.AddField(
            model_name='childcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/child_category', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/category', verbose_name='تصویر'),
        ),
    ]
