# Generated by Django 4.2.30 on 2026-04-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_alter_childcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainCategory',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='ChildCategory',
        ),
    ]
