# Generated by Django 4.2.30 on 2026-04-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='مقدار تخفیف (درصد)'),
        ),
    ]
