# Generated by Django 4.2.30 on 2026-04-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_alter_discount_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.IntegerField(verbose_name='مقدار تخفیف (درصد)'),
        ),
    ]
