# Generated by Django 4.2.30 on 2026-04-18 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0014_alter_discount_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='duration_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
