# Generated by Django 4.2.30 on 2026-04-18 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_discount_duration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='duration_time',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='زمان باقی مانده'),
        ),
    ]
