# Generated by Django 4.2.30 on 2026-04-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_alter_discount_duration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.discount', verbose_name='تخفیف'),
        ),
    ]
