# Generated by Django 4.2.30 on 2026-04-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0018_remove_product_category_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('url_title', models.SlugField(max_length=100, unique=True, verbose_name='لینک')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/category/child_category', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('is_delete', models.BooleanField(default=False, verbose_name='حذف شده /نشده')),
                ('main_category', models.ManyToManyField(to='product_module.category', verbose_name='دسته بندی اصلی')),
            ],
            options={
                'verbose_name': 'دسته بندی فرزند',
                'verbose_name_plural': 'دسته بندی های فرزند',
            },
        ),
    ]
