# Generated by Django 4.2.30 on 2026-04-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0019_childcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChildCategory',
        ),
    ]
