# Generated by Django 4.2.30 on 2026-04-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0020_delete_childcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/ads', verbose_name='تصویر')),
                ('url_title', models.SlugField(unique=True, verbose_name='لینک')),
            ],
        ),
    ]
