# Generated by Django 4.2.30 on 2026-04-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0021_ads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'verbose_name': 'تیلیغ', 'verbose_name_plural': 'تبلیغات'},
        ),
        migrations.AddField(
            model_name='ads',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
    ]
