# Generated by Django 4.2.30 on 2026-04-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0022_alter_ads_options_ads_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='لینک محصول'),
        ),
        migrations.AddField(
            model_name='slider',
            name='url_title',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='لینک'),
        ),
    ]
