# Generated by Django 4.2.30 on 2026-04-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0023_product_url_title_slider_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_title',
            field=models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='لینک محصول'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='url_title',
            field=models.CharField(max_length=200, unique=True, verbose_name='لینک'),
        ),
    ]
