# Generated by Django 4.2.30 on 2026-04-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0028_remove_brand_product_brand_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'برند', 'verbose_name_plural': 'برندها'},
        ),
    ]
