# Generated by Django 4.2.30 on 2026-04-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0029_alter_brand_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.category', verbose_name='دسته بندی'),
        ),
    ]
