# Generated by Django 4.2.30 on 2026-04-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0030_remove_brand_category_brand_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_title',
            field=models.CharField(blank=True, db_index=True, max_length=200, unique=True, verbose_name='لینک محصول'),
        ),
    ]
