# Generated by Django 4.2.30 on 2026-04-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0031_alter_product_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='لینک محصول'),
        ),
    ]
