# Generated by Django 4.2.30 on 2026-04-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0033_alter_product_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_title',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='لینک محصول'),
        ),
    ]
