# Generated by Django 4.2.30 on 2026-04-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0040_alter_product_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_title',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=800, unique=True, verbose_name='لینک محصول'),
        ),
    ]
