# Generated by Django 4.2.30 on 2026-04-20 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0041_alter_product_url_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('category_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.mainsettings', verbose_name='دسته بندی نتظیمات')),
            ],
        ),
    ]
