# Generated by Django 4.2.30 on 2026-04-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0042_mainsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainsettings',
            options={'verbose_name': 'تنظیمات محصول', 'verbose_name_plural': 'تنظیمات محصولات'},
        ),
    ]
