# Generated by Django 4.2.30 on 2026-04-20 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0043_alter_mainsettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='category_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.mainsettings', verbose_name='دسته بندی نتظیمات'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
