# Generated by Django 4.2.30 on 2026-04-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0044_alter_mainsettings_category_setting_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainSettings',
        ),
    ]
