# Generated by Django 4.2.30 on 2026-04-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0045_delete_mainsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'مشخصه اصلی',
                'verbose_name_plural': 'مشخصات اصلی',
            },
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100, verbose_name='ویژگی محصول')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول')),
                ('selected_attributes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.mainattributes', verbose_name='مشخصه')),
            ],
        ),
    ]
