# Generated by Django 4.2.30 on 2026-04-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0046_mainattributes_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributes',
            options={'verbose_name': 'ویژگی محصول', 'verbose_name_plural': 'ویژگی های محصول'},
        ),
    ]
