# Generated by Django 4.2.30 on 2026-04-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0047_alter_attributes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainattributes',
            name='category_attributes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.mainattributes', verbose_name='دسته بندی مشخصات'),
        ),
    ]
