# Generated by Django 4.2.30 on 2026-04-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0048_mainattributes_category_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی مشخصات',
                'verbose_name_plural': 'دسته بندی های مشخثات',
            },
        ),
        migrations.AlterField(
            model_name='mainattributes',
            name='category_attributes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.categoryattributes', verbose_name='دسته بندی مشخصات'),
        ),
    ]
