# Generated by Django 4.2.30 on 2026-04-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0049_categoryattributes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryattributes',
            options={'verbose_name': 'دسته بندی مشخصات', 'verbose_name_plural': 'دسته بندی های مشخصات'},
        ),
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.categoryattributes', verbose_name='مشخصات'),
        ),
    ]
