# Generated by Django 4.2.30 on 2026-04-22 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0050_alter_categoryattributes_options_product_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='category_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.categoryattributes', verbose_name='دسته بندی مشخصات'),
        ),
    ]
