# Generated by Django 4.2.30 on 2026-04-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0051_attributes_category_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='category_attribute',
        ),
    ]
