# Generated by Django 4.2.30 on 2026-04-23 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0052_remove_attributes_category_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='selected_attributes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attribute',
        ),
        migrations.AddField(
            model_name='attributes',
            name='main_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product_module.mainattributes', verbose_name='مشخصه اصلی'),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='attribute',
            field=models.CharField(max_length=100, verbose_name='مقدار ویژگی'),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product_module.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='mainattributes',
            name='category_attributes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_attributes', to='product_module.categoryattributes', verbose_name='دسته بندی مشخصات'),
        ),
    ]
