# Generated by Django 4.2.30 on 2026-04-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0053_remove_attributes_selected_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_attribute',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.categoryattributes', verbose_name='دسته بندی مشخصات'),
        ),
    ]
