# Generated by Django 4.2.30 on 2026-04-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0054_product_category_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام انگلیسی محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام فارسی محصول'),
        ),
    ]
