# Generated by Django 4.2.30 on 2026-04-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0055_remove_product_title_product_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=250, verbose_name='نام فارسی محصول'),
        ),
    ]
