# Generated by Django 4.2.30 on 2026-04-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0058_alter_product_title_fa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title_fa',
            new_name='title',
        ),
    ]
