# Generated by Django 4.2.30 on 2026-04-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0059_rename_title_fa_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
