# Generated by Django 4.2.30 on 2026-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0060_remove_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(default='a', max_length=250, verbose_name='نام فارسی محصول'),
        ),
    ]
