# Generated by Django 4.2.30 on 2026-04-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0062_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
    ]
