# Generated by Django 4.2.30 on 2026-04-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0067_remove_rating_comment_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
    ]
