# Generated by Django 4.2.30 on 2026-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0071_color_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=250, verbose_name='نام فارسی محصول'),
        ),
    ]
