# Generated by Django 4.2.30 on 2026-05-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0073_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='url_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس'),
        ),
    ]
