# Generated by Django 4.2.30 on 2026-05-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0074_color_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='کد رنگی'),
        ),
    ]
