# Generated by Django 4.2.30 on 2026-05-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0076_comment_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
