# Generated by Django 4.2.30 on 2026-06-02 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0080_attribute_productattribute_specificationgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product_module.specificationgroup', verbose_name='گروه مشخصات دسته بندی'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان مشخصات'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.attribute', verbose_name='عنوان مشخصات'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='product_module.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='value',
            field=models.CharField(max_length=255, verbose_name='مشخصه محصول'),
        ),
        migrations.AlterField(
            model_name='specificationgroup',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_groups', to='product_module.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='specificationgroup',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
