# Generated by Django 4.2.30 on 2026-06-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0081_alter_attribute_group_alter_attribute_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'عنوان مشخصه', 'verbose_name_plural': 'عنوان مشخصات'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'مشخصه', 'verbose_name_plural': 'مشخصات'},
        ),
        migrations.AlterModelOptions(
            name='specificationgroup',
            options={'verbose_name': 'گروه مشخصات', 'verbose_name_plural': 'گروه مشخصات'},
        ),
    ]
