# Generated by Django 4.2.30 on 2026-06-02 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0083_productattributevalue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'ویژگی محصول', 'verbose_name_plural': 'ویژگی های محصول'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'مشخصه', 'verbose_name_plural': 'مشخصات'},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='product_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='product_module.productattribute', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(max_length=255, verbose_name='مشخصه محصول'),
        ),
    ]
