# Generated by Django 4.2.30 on 2026-06-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0086_alter_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت کامنت'),
        ),
    ]
