# Generated by Django 4.2.30 on 2026-06-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0087_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('pending', 'رد شده')], max_length=50, null=True, verbose_name='وضعیت کامنت'),
        ),
    ]
