# Generated by Django 4.2.30 on 2026-06-20 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0092_slider_brand_slider_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.category', verbose_name='سته بندی'),
        ),
    ]
