# Generated by Django 4.2.30 on 2026-06-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0093_alter_slider_brand_alter_slider_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.category', verbose_name='دسته بندی'),
        ),
    ]
