# Generated by Django 4.2.30 on 2026-05-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailorder',
            name='add_to_order_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ اضافه شدن به سبد خرید'),
        ),
    ]
