# Generated by Django 4.2.30 on 2026-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0002_detailorder_add_to_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorder',
            name='add_to_order_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ اضافه شدن به سبد خرید'),
        ),
    ]
