# Generated by Django 4.2.30 on 2026-05-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0079_alter_product_brand'),
        ('order_module', '0003_alter_detailorder_add_to_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='product_module.product', verbose_name='محصول'),
        ),
    ]
