# Generated by Django 4.2.30 on 2026-06-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0007_alter_detailorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailorder',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'پرداخت شده'), ('delivered', 'تحویل داده شده')], default='paid', max_length=100, null=True, verbose_name='وضعیت محصول'),
        ),
    ]
