# Generated by Django 4.2.30 on 2026-06-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0008_alter_detailorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده / نشده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
