# Generated by Django 4.2.30 on 2026-06-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0010_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mobile',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
