# Generated by Django 4.2.30 on 2026-04-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('url_site', models.CharField(max_length=100, verbose_name='دامنه سایت')),
                ('is_main_setting', models.BooleanField(default=True, verbose_name='تنظیمات اصلی')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('phone_number', models.CharField(max_length=50, verbose_name='شماره تلفن')),
                ('copy_right', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن کپی رایت')),
                ('site_logo', models.ImageField(upload_to='images/site_settings', verbose_name='لوگوی سایت')),
            ],
        ),
    ]
