# Generated by Django 4.2.30 on 2026-04-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headersettings',
            options={'verbose_name': 'تنظیم هدر', 'verbose_name_plural': 'تنظیمات هدر سایت'},
        ),
        migrations.AlterField(
            model_name='headersettings',
            name='site_logo',
            field=models.FileField(upload_to='images/site_settings', verbose_name='لوگوی سایت'),
        ),
    ]
