# Generated by Django 4.2.30 on 2026-05-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0002_alter_headersettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل'),
        ),
    ]
