# Generated by Django 4.2.30 on 2026-05-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0003_headersettings_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن درباره ما')),
                ('ads_text', models.CharField(blank=True, max_length=150, null=True, verbose_name='شعار تبلیغاتی')),
            ],
            options={
                'verbose_name': 'درباره ما',
                'verbose_name_plural': 'درباره ما',
            },
        ),
    ]
