# Generated by Django 4.2.30 on 2026-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0004_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='تصویر'),
        ),
    ]
