# Generated by Django 4.2.30 on 2026-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0005_aboutus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='ads_text',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.AddField(
            model_name='headersettings',
            name='image_about_us',
            field=models.ImageField(blank=True, null=True, upload_to='images/about_us', verbose_name='تصویر'),
        ),
    ]
