# Generated by Django 4.2.30 on 2026-05-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0006_remove_aboutus_ads_text_remove_aboutus_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='text_history',
            field=models.TextField(blank=True, null=True, verbose_name='متن درباره ما'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='title_history',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان'),
        ),
    ]
