# Generated by Django 4.2.30 on 2026-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0007_headersettings_text_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
