# Generated by Django 4.2.30 on 2026-05-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0008_aboutus_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='errosPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images/errors_images')),
            ],
            options={
                'verbose_name': 'تصویر خطا',
                'verbose_name_plural': 'تصاویر خطاها',
            },
        ),
    ]
