# Generated by Django 4.2.30 on 2026-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0009_errospicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errospicture',
            name='image',
            field=models.FileField(upload_to='images/errors_images'),
        ),
    ]
