# Generated by Django 4.2.30 on 2026-05-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0010_alter_errospicture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='errospicture',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='متن ارور'),
        ),
        migrations.AlterField(
            model_name='errospicture',
            name='image',
            field=models.FileField(upload_to='images/errors_images', verbose_name='تصویر'),
        ),
    ]
