# Generated by Django 4.2.30 on 2026-05-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0011_errospicture_text_alter_errospicture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errospicture',
            name='text',
            field=models.CharField(max_length=200, verbose_name='متن ارور'),
        ),
    ]
