# Generated by Django 4.2.30 on 2026-06-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0012_alter_errospicture_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان اصلی')),
                ('url_title', models.CharField(max_length=100, verbose_name='عنوان ذر url')),
                ('footer_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings_site_module.footer', verbose_name='آیتم هر عنوان')),
            ],
            options={
                'verbose_name': 'فوتر',
                'verbose_name_plural': 'فوتر',
            },
        ),
    ]
