# Generated by Django 4.2.30 on 2026-06-22 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0013_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='footer_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings_site_module.footer', verbose_name='آیتم هر عنوان'),
        ),
    ]
