# Generated by Django 4.2.30 on 2026-06-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0014_alter_footer_footer_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='آیتم هر عنوان در فوتر')),
                ('url_title', models.CharField(max_length=150, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'آیتم فوتر',
                'verbose_name_plural': 'آیتم های فوتر',
            },
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'عنوان فوتر', 'verbose_name_plural': 'عناوین فوتر'},
        ),
        migrations.RemoveField(
            model_name='footer',
            name='footer_item',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='url_title',
        ),
    ]
