# Generated by Django 4.2.30 on 2026-06-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_site_module', '0015_footeritem_alter_footer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footeritem',
            name='footer_main_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings_site_module.footer', verbose_name='عنوان اصلی'),
        ),
    ]
