# Generated by Django 4.2.30 on 2026-05-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
            ],
        ),
    ]
