# Generated by Django 4.2.30 on 2026-05-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس های با ما'},
        ),
    ]
