# Generated by Django 4.2.30 on 2026-04-17 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیفات'},
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='name',
            new_name='title',
        ),
    ]
