# Generated by Django 4.2.30 on 2026-04-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_alter_discount_options_rename_name_discount_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
