# Generated by Django 4.2.30 on 2026-06-16 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_module', '0003_remove_product_discount_delete_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='متن جستجو شده')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='زمان سرچ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارب')),
            ],
            options={
                'verbose_name': 'تاریخ جستجو',
                'verbose_name_plural': 'تاریخچه جستجوها',
            },
        ),
    ]
