# Generated by Django 4.2.30 on 2026-04-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_remove_user_phone_number_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_account_code',
            field=models.IntegerField(max_length=72, verbose_name='کد فعال سازی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='ایمیل'),
        ),
    ]
