# Generated by Django 4.2.30 on 2026-04-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_user_active_account_code_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_account_code',
            field=models.CharField(max_length=72, verbose_name='کد فعال سازی'),
        ),
    ]
