# Generated by Django 4.2.30 on 2026-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0006_user_about_user_user_birthday_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن'),
        ),
    ]
