# Generated by Django 4.2.30 on 2026-06-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0009_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'ترجیح میدهم نگویم')], max_length=20, null=True, verbose_name='جنسیت'),
        ),
    ]
