# Generated by Django 4.2.30 on 2026-06-11 12:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0013_alter_city_name_alter_city_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='کد پستی باید دقیقا ۱۰ رقم باشد.', regex='^\\d{10}$')], verbose_name='کد پستی')),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره همراه باید با 09 شروع شده و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تلفن')),
                ('full_address', models.TextField(verbose_name='آدرس کامل')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_module.city', verbose_name='شهر')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_module.province', verbose_name='استان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
