# Generated by Django 4.2.30 on 2026-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0014_remove_user_address_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس ها'},
        ),
        migrations.AddField(
            model_name='address',
            name='receiver_name',
            field=models.CharField(default='khl', max_length=100, verbose_name='نام گیرنده'),
        ),
    ]
