# Generated by Django 4.2.30 on 2026-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0015_alter_address_options_address_receiver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='receiver_name',
            field=models.CharField(max_length=100, verbose_name='نام گیرنده'),
        ),
    ]
