# Generated by Django 4.2.30 on 2026-06-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0017_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.BooleanField(default=False, verbose_name='عنوان آدرس'),
        ),
    ]
