# Generated by Django 4.2.30 on 2026-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0018_address_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان آدرس'),
        ),
    ]
