# Generated by Django 4.2.30 on 2026-06-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0019_alter_address_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number',
        ),
    ]
