# Generated by Django 4.2.30 on 2026-06-14 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0021_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره همراه باید با 09 شروع شده و ۱۱ رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
